{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devmatrix.fullname" . }}-secrets
  labels:
    {{- include "devmatrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PostgreSQL credentials
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.existingSecret | default "CHANGE_ME_IN_PRODUCTION" | quote }}

  # API Keys
  anthropic-api-key: {{ .Values.secrets.data.anthropicApiKey | default "CHANGE_ME_IN_PRODUCTION" | quote }}
  openai-api-key: {{ .Values.secrets.data.openaiApiKey | default "CHANGE_ME_IN_PRODUCTION" | quote }}
  google-api-key: {{ .Values.secrets.data.googleApiKey | default "CHANGE_ME_IN_PRODUCTION" | quote }}

  # Redis password (optional)
  redis-password: ""
{{- end }}
