apiVersion: v1
kind: Service
metadata:
  name: {{ include "devmatrix.fullname" . }}
  labels:
    {{- include "devmatrix.labels" . | nindent 4 }}
    component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "devmatrix.selectorLabels" . | nindent 4 }}
    component: api
