"""
API - Production-Ready FastAPI Application

Generated by DevMatrix with complete observability infrastructure.
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException

from src.core.config import get_settings
from src.core.logging import setup_logging
from src.core.middleware import (
    RequestIDMiddleware,
    MetricsMiddleware,
    SecurityHeadersMiddleware
)
from src.core.exception_handlers import (
    global_exception_handler,
    http_exception_handler,
    validation_exception_handler
)
from src.api.routes import health, metrics

from src.api.routes import product
from src.api.routes import customer
from src.api.routes import cart
from src.api.routes import order

import structlog

# Load settings
settings = get_settings()

# Configure logging
setup_logging(settings.log_level)
logger = structlog.get_logger(__name__)

# Initialize FastAPI app
# CRITICAL: /docs and /redoc are ALWAYS enabled for development, testing, and internal use
# To disable in production, use reverse proxy (nginx, ALB, etc), not by disabling in code
app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    debug=settings.debug,
    docs_url="/docs",  # Always enabled
    redoc_url="/redoc"  # Always enabled
)

# Register exception handlers
app.add_exception_handler(Exception, global_exception_handler)
app.add_exception_handler(StarletteHTTPException, http_exception_handler)
app.add_exception_handler(RequestValidationError, validation_exception_handler)

# Add middleware (order matters - last added is executed first)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(MetricsMiddleware)
app.add_middleware(RequestIDMiddleware)

# Register routers
app.include_router(health.router)
app.include_router(metrics.router)

app.include_router(product.router)
app.include_router(customer.router)
app.include_router(cart.router)
app.include_router(order.router)


@app.on_event("startup")
async def startup_event():
    """
    Application startup event.

    Logs application startup with configuration info.
    """
    logger.info(
        "application_starting",
        app_name=settings.app_name,
        version=settings.app_version,
        environment=settings.environment,
        debug=settings.debug,
        log_level=settings.log_level
    )


@app.on_event("shutdown")
async def shutdown_event():
    """
    Application shutdown event.

    Logs graceful shutdown.
    """
    logger.info("application_shutdown", app_name=settings.app_name)


@app.get("/")
async def root():
    """
    Root endpoint - API information.

    Returns:
        dict: API metadata
    """
    return {
        "name": settings.app_name,
        "version": settings.app_version,
        "status": "running",
        "docs": "/docs",
        "health": "/health/health",
        "ready": "/health/ready",
        "metrics": "/metrics/metrics"
    }