"""
Tests for AcceptanceTestGenerator - Automatic test generation from requirements

Tests cover:
- Test generation from requirements
- Test type determination (contract, invariant, case)
- Preconditions/postconditions generation
- Test code template filling
- Edge cases (no requirements, invalid requirements)
"""

import pytest
from uuid import uuid4

from src.mge.v2.acceptance.test_generator import (
    AcceptanceTestGenerator,
    AcceptanceTest,
    TestType,
    TestGenerationResult
)


@pytest.fixture
def generator():
    """Create AcceptanceTestGenerator instance"""
    return AcceptanceTestGenerator()


@pytest.fixture
def masterplan_id():
    """Generate test masterplan ID"""
    return uuid4()


# ============================================================
# Test: Basic Test Generation
# ============================================================

def test_generate_from_single_requirement(generator, masterplan_id):
    """Test generating tests from single requirement"""

    requirements = [
        {
            "id": "REQ-001",
            "priority": "MUST",
            "description": "User can login with email/password",
            "type": "case"
        }
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    assert result.masterplan_id == masterplan_id
    assert result.total_generated == 1
    assert len(result.case_tests) == 1
    assert len(result.contract_tests) == 0
    assert len(result.invariant_tests) == 0
    assert len(result.generation_errors) == 0


def test_generate_from_multiple_requirements(generator, masterplan_id):
    """Test generating tests from multiple requirements"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "User login", "type": "case"},
        {"id": "REQ-002", "priority": "SHOULD", "description": "API endpoint", "type": "contract"},
        {"id": "REQ-003", "priority": "MUST", "description": "System invariant", "type": "invariant"},
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    assert result.total_generated == 3
    assert len(result.case_tests) == 1
    assert len(result.contract_tests) == 1
    assert len(result.invariant_tests) == 1


# ============================================================
# Test: Test Type Determination
# ============================================================

def test_determine_contract_test_from_explicit_type(generator, masterplan_id):
    """Test contract test detection from explicit type hint"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Login endpoint", "type": "contract"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    assert len(result.contract_tests) == 1
    assert result.contract_tests[0].test_type == TestType.CONTRACT


def test_determine_contract_test_from_description(generator, masterplan_id):
    """Test contract test detection from description keywords"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "API endpoint returns user data"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should detect "API" and "endpoint" keywords and generate contract test
    assert len(result.contract_tests) >= 1


def test_determine_invariant_test_from_explicit_type(generator, masterplan_id):
    """Test invariant test detection from explicit type hint"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Data consistency", "type": "invariant"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    assert len(result.invariant_tests) == 1
    assert result.invariant_tests[0].test_type == TestType.INVARIANT


def test_determine_invariant_test_from_description(generator, masterplan_id):
    """Test invariant test detection from description keywords"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "System must always maintain data consistency"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should detect "always" keyword and generate invariant test
    assert len(result.invariant_tests) >= 1


def test_determine_case_test_default(generator, masterplan_id):
    """Test that case tests are generated by default"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Simple requirement"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should default to case test when no specific type detected
    assert len(result.case_tests) >= 1


def test_multiple_test_types_from_single_requirement(generator, masterplan_id):
    """Test generating multiple test types from single requirement"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "API endpoint must always maintain consistency"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should detect both "API endpoint" (contract) and "always" (invariant)
    # Plus default case test
    assert result.total_generated >= 2


# ============================================================
# Test: Test Generation Details
# ============================================================

def test_generated_test_has_correct_fields(generator, masterplan_id):
    """Test that generated test has all required fields"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "User login"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    all_tests = generator.get_all_tests(result)

    assert len(all_tests) > 0

    test = all_tests[0]
    assert test.test_id is not None
    assert test.test_type is not None
    assert test.requirement_id == "REQ-001"
    assert test.description == "User login"
    assert test.test_code is not None
    assert test.expected_outcome is not None
    assert test.preconditions is not None
    assert test.postconditions is not None


def test_generated_test_has_executable_code(generator, masterplan_id):
    """Test that generated test contains executable code"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Login test", "type": "case"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    test = result.case_tests[0]
    assert "async def test_case_" in test.test_code
    assert "assert" in test.test_code


def test_contract_test_code_structure(generator, masterplan_id):
    """Test contract test code structure"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "API test", "type": "contract"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    test = result.contract_tests[0]
    assert "async def test_contract_" in test.test_code
    assert "Preconditions" in test.test_code
    assert "Postconditions" in test.test_code


def test_invariant_test_code_structure(generator, masterplan_id):
    """Test invariant test code structure"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Invariant", "type": "invariant"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    test = result.invariant_tests[0]
    assert "async def test_invariant_" in test.test_code
    assert "invariant" in test.test_code.lower()


# ============================================================
# Test: Priority Handling
# ============================================================

def test_requirement_priority_must(generator, masterplan_id):
    """Test MUST priority handling"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Critical feature"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    all_tests = generator.get_all_tests(result)

    assert all(test.requirement_priority.value == "must" for test in all_tests)


def test_requirement_priority_should(generator, masterplan_id):
    """Test SHOULD priority handling"""

    requirements = [
        {"id": "REQ-001", "priority": "SHOULD", "description": "Nice to have"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    all_tests = generator.get_all_tests(result)

    assert all(test.requirement_priority.value == "should" for test in all_tests)


def test_requirement_priority_default_to_should(generator, masterplan_id):
    """Test priority defaults to SHOULD for invalid values"""

    requirements = [
        {"id": "REQ-001", "priority": "INVALID", "description": "Feature"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    all_tests = generator.get_all_tests(result)

    # Should default to SHOULD for invalid priority
    assert all(test.requirement_priority.value == "should" for test in all_tests)


# ============================================================
# Test: Preconditions and Postconditions
# ============================================================

def test_contract_test_preconditions(generator, masterplan_id):
    """Test contract test preconditions generation"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "API", "type": "contract"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.contract_tests[0]

    assert len(test.preconditions) > 0
    assert "System is in valid state" in test.preconditions
    assert "API endpoint is available" in test.preconditions


def test_invariant_test_preconditions(generator, masterplan_id):
    """Test invariant test preconditions generation"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Invariant", "type": "invariant"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.invariant_tests[0]

    assert len(test.preconditions) > 0
    assert "System invariants are satisfied" in test.preconditions


def test_contract_test_postconditions(generator, masterplan_id):
    """Test contract test postconditions generation"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "API", "type": "contract"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.contract_tests[0]

    assert len(test.postconditions) > 0
    assert "Response format matches contract" in test.postconditions
    assert "No side effects observed" in test.postconditions


# ============================================================
# Test: Expected Outcomes
# ============================================================

def test_contract_test_expected_outcome(generator, masterplan_id):
    """Test contract test expected outcome"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "User API", "type": "contract"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.contract_tests[0]

    assert "API contract verified" in test.expected_outcome


def test_invariant_test_expected_outcome(generator, masterplan_id):
    """Test invariant test expected outcome"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Consistency", "type": "invariant"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.invariant_tests[0]

    assert "System invariant maintained" in test.expected_outcome


def test_case_test_expected_outcome(generator, masterplan_id):
    """Test case test expected outcome"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Login flow", "type": "case"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    test = result.case_tests[0]

    assert "Use case completed successfully" in test.expected_outcome


# ============================================================
# Test: Edge Cases and Error Handling
# ============================================================

def test_generate_from_empty_requirements(generator, masterplan_id):
    """Test generating tests from empty requirements list"""

    requirements = []

    result = generator.generate_from_requirements(masterplan_id, requirements)

    assert result.total_generated == 0
    assert len(result.contract_tests) == 0
    assert len(result.invariant_tests) == 0
    assert len(result.case_tests) == 0
    assert len(result.generation_errors) == 0


def test_generate_with_missing_id(generator, masterplan_id):
    """Test handling requirement with missing id"""

    requirements = [
        {"priority": "MUST", "description": "Feature without ID"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should still generate test, using "UNKNOWN" as fallback
    assert result.total_generated >= 1


def test_generate_with_missing_description(generator, masterplan_id):
    """Test handling requirement with missing description"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # Should still generate test with empty description
    assert result.total_generated >= 1


def test_get_all_tests_combines_all_types(generator, masterplan_id):
    """Test get_all_tests returns all test types combined"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Contract", "type": "contract"},
        {"id": "REQ-002", "priority": "MUST", "description": "Invariant", "type": "invariant"},
        {"id": "REQ-003", "priority": "MUST", "description": "Case", "type": "case"},
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    all_tests = generator.get_all_tests(result)

    assert len(all_tests) == result.total_generated
    assert len(all_tests) == len(result.contract_tests) + len(result.invariant_tests) + len(result.case_tests)


# ============================================================
# Test: Test Generation Result
# ============================================================

def test_test_generation_result_to_dict(generator, masterplan_id):
    """Test TestGenerationResult to_dict method"""

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Feature", "type": "case"}
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)
    result_dict = result.to_dict()

    assert "masterplan_id" in result_dict
    assert "total_generated" in result_dict
    assert "contract_tests" in result_dict
    assert "invariant_tests" in result_dict
    assert "case_tests" in result_dict
    assert "generation_errors" in result_dict
    assert result_dict["total_generated"] == 1


def test_test_generation_errors_captured(generator, masterplan_id):
    """Test that generation errors are captured"""

    # Create a requirement that might cause issues
    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Normal requirement"},
    ]

    result = generator.generate_from_requirements(masterplan_id, requirements)

    # This should succeed without errors
    assert len(result.generation_errors) == 0


def test_test_generation_error_handling(generator, masterplan_id):
    """Test that errors during generation are properly caught and logged"""
    from unittest.mock import patch

    requirements = [
        {"id": "REQ-001", "priority": "MUST", "description": "Test requirement"},
    ]

    # Mock _generate_test to raise an exception
    with patch.object(generator, '_generate_test', side_effect=Exception("Test error")):
        result = generator.generate_from_requirements(masterplan_id, requirements)

    # Error should be captured
    assert len(result.generation_errors) == 1
    assert "Failed to generate tests for REQ-001" in result.generation_errors[0]
    assert "Test error" in result.generation_errors[0]
    assert result.total_generated == 0


# ============================================================
# Test: Template Loading
# ============================================================

def test_templates_loaded_for_all_types(generator):
    """Test that templates are loaded for all test types"""

    templates = generator._test_templates

    assert TestType.CONTRACT in templates
    assert TestType.INVARIANT in templates
    assert TestType.CASE in templates

    # Templates should contain async def
    assert "async def" in templates[TestType.CONTRACT]
    assert "async def" in templates[TestType.INVARIANT]
    assert "async def" in templates[TestType.CASE]
