"""
Configuration module for DevMatrix.

This module provides centralized configuration management with environment
variable overrides and validation.
"""

from src.config.constants import (
    DEFAULT_MAX_TOKENS,
    STREAMING_MAX_TOKENS,
    CHAT_MAX_TOKENS,
    DEFAULT_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_REQUEST_TIMEOUT,
    HEALTH_CHECK_TIMEOUT,
    LLM_API_TIMEOUT,
    TASK_TIMEOUT_SHORT,
    TASK_TIMEOUT_MEDIUM,
    TASK_TIMEOUT_LONG,
    TASK_TIMEOUT_MAX,
    TEST_EXECUTION_TIMEOUT,
    CACHE_TTL_SHORT,
    CACHE_TTL_MEDIUM,
    CACHE_TTL_LONG,
    DEFAULT_CACHE_TTL,
    LLM_CACHE_TTL,
    AGENT_CACHE_TTL,
    ARTIFACT_TTL,
    CHECKPOINT_TTL,
    API_PORT,
    UI_PORT,
    POSTGRES_PORT,
    REDIS_PORT,
    API_HOST,
    POSTGRES_HOST,
    REDIS_HOST,
    SOCKET_CONNECT_TIMEOUT,
    SOCKET_TIMEOUT,
    CHROMADB_HOST,
    CHROMADB_PORT,
    EMBEDDING_MODEL,
    EMBEDDING_DEVICE,
    # RAG Configuration
    RAG_TOP_K,
    RAG_SIMILARITY_THRESHOLD,
    RAG_SIMILARITY_THRESHOLD_CURATED,
    RAG_SIMILARITY_THRESHOLD_PROJECT,
    RAG_SIMILARITY_THRESHOLD_STANDARDS,
    RAG_ENABLE_FEEDBACK,
    CHROMADB_COLLECTION_NAME,
    CHROMADB_DISTANCE_METRIC,
    RAG_BATCH_SIZE,
    RAG_MAX_CONTEXT_LENGTH,
    RAG_CACHE_ENABLED,
    # Retry Configuration
    DEFAULT_MAX_RETRIES,
    RETRY_INITIAL_DELAY,
    RETRY_MAX_DELAY,
    # Helper Functions
    get_config_summary,
    validate_config,
    get_task_timeout,
)

__all__ = [
    # LLM Configuration
    "DEFAULT_MAX_TOKENS",
    "STREAMING_MAX_TOKENS",
    "CHAT_MAX_TOKENS",
    "DEFAULT_MODEL",
    "DEFAULT_TEMPERATURE",
    # Network Configuration
    "API_HOST",
    "API_PORT",
    "UI_PORT",
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "REDIS_HOST",
    "REDIS_PORT",
    "CHROMADB_HOST",
    "CHROMADB_PORT",
    # RAG Configuration
    "EMBEDDING_MODEL",
    "RAG_TOP_K",
    "RAG_SIMILARITY_THRESHOLD",
    "RAG_SIMILARITY_THRESHOLD_CURATED",
    "RAG_SIMILARITY_THRESHOLD_PROJECT",
    "RAG_SIMILARITY_THRESHOLD_STANDARDS",
    "RAG_ENABLE_FEEDBACK",
    "CHROMADB_COLLECTION_NAME",
    "CHROMADB_DISTANCE_METRIC",
    "RAG_BATCH_SIZE",
    "RAG_MAX_CONTEXT_LENGTH",
    "RAG_CACHE_ENABLED",
    # Cache Configuration
    "DEFAULT_CACHE_TTL",
    "LLM_CACHE_TTL",
    "AGENT_CACHE_TTL",
    # Timeout Configuration
    "DEFAULT_REQUEST_TIMEOUT",
    "LLM_API_TIMEOUT",
    "TASK_TIMEOUT_SHORT",
    "TASK_TIMEOUT_MEDIUM",
    "TASK_TIMEOUT_LONG",
    # Retry Configuration
    "DEFAULT_MAX_RETRIES",
    "RETRY_INITIAL_DELAY",
    "RETRY_MAX_DELAY",
    # Helper Functions
    "get_config_summary",
    "validate_config",
    "get_task_timeout",
]
