apiVersion: v1
kind: ConfigMap
metadata:
  name: devmatrix-config
  namespace: devmatrix
  labels:
    app: devmatrix
data:
  # Application configuration
  app.yaml: |
    environment: production
    log_level: INFO
    log_format: json

    # API configuration
    api:
      host: 0.0.0.0
      port: 8000
      workers: 4
      timeout: 300
      cors_origins:
        - https://devmatrix.example.com
        - https://api.devmatrix.example.com

    # Redis configuration
    redis:
      host: devmatrix-redis
      port: 6379
      db: 0
      ttl: 7200  # 2 hours
      max_connections: 50

    # PostgreSQL configuration
    postgres:
      host: devmatrix-postgres
      port: 5432
      pool_size: 20
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 3600

    # Performance tuning
    performance:
      cache_enabled: true
      cache_ttl: 3600
      max_workers: 4
      request_timeout: 300

    # Monitoring
    monitoring:
      prometheus_enabled: true
      health_check_interval: 30
      metrics_port: 8000
