apiVersion: v1
kind: ServiceAccount
metadata:
  name: devmatrix-api
  namespace: devmatrix
  labels:
    app: devmatrix
    component: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devmatrix-api
  namespace: devmatrix
  labels:
    app: devmatrix
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devmatrix-api
  namespace: devmatrix
  labels:
    app: devmatrix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devmatrix-api
subjects:
- kind: ServiceAccount
  name: devmatrix-api
  namespace: devmatrix
