# Development environment overrides

global:
  environment: development

api:
  replicaCount: 1

  image:
    pullPolicy: Always
    tag: "dev"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  autoscaling:
    enabled: false

postgresql:
  enabled: true

  primary:
    persistence:
      enabled: false

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

redis:
  enabled: true

  master:
    persistence:
      enabled: false

    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "250m"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: dev.devmatrix.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: devmatrix-dev-tls
      hosts:
        - dev.devmatrix.example.com

config:
  logLevel: DEBUG
  logFormat: json

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false

networkPolicy:
  enabled: false
