# Staging environment overrides

global:
  environment: staging

api:
  replicaCount: 2

  image:
    pullPolicy: IfNotPresent
    tag: "staging"

  resources:
    requests:
      memory: "384Mi"
      cpu: "200m"
    limits:
      memory: "768Mi"
      cpu: "750m"

  autoscaling:
    enabled: false

postgresql:
  enabled: true

  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard"

    resources:
      requests:
        memory: "384Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "750m"

redis:
  enabled: true

  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "standard"

    resources:
      requests:
        memory: "192Mi"
        cpu: "75m"
      limits:
        memory: "384Mi"
        cpu: "375m"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "50"
  hosts:
    - host: staging.devmatrix.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: devmatrix-staging-tls
      hosts:
        - staging.devmatrix.example.com

config:
  logLevel: INFO
  logFormat: json

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 60s

networkPolicy:
  enabled: false
